apiVersion: v1
name: keycloak
version: 15.1.3
appVersion: 15.0.2
description: Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
sources:
  - https://github.com/catrielmuller/codecentric-helm-charts
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
maintainers:
  - name: Catriel Müller
    email: catrielmuller@gmail.com
